version: '3'

networks:
  wordpress:

services:

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - php
      - mysql
    volumes:
      - ../wordpress:/var/www/html/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wordpress

  mysql:
    image: mysql:5.7.29
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - wordpress

  # php:
  #   build:
  #     context: .
  #     dockerfile: php.dockerfile
  #   volumes:
  #     - ../wordpress:/var/www/html
  #   networks:
  #     - wordpress

  wp:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ../wordpress:/var/www/html:delegated
    entrypoint: ['wp', '--allow-root']

  # php:
  #   build: 
  #     context: .
  #     dockerfile: laravel.dockerfile
  #   volumes:
  #     - ../V4.7.8:/var/www/html:delegated
  #   networks:
  #     - wordpress
